datasets:
  qvh: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /scratch_xijun/data/QVH/qvh/train.json
          storage: /scratch_xijun/data/QVH/qvh/train.json
        val:
          url: /scratch_xijun/data/QVH/qvh/val.json
          storage: /scratch_xijun/data/QVH/qvh/val.json
        test:
          url: /scratch_xijun/data/QVH/qvh/test.json
          storage: /scratch_xijun/data/QVH/qvh/test.json
      videos:
        storage: /scratch_xijun/data/QVH/videos/
